services:
  experiment:
    build: .
    container_name: rbtm-experiment
    restart: unless-stopped
    depends_on:
      tomograph_server:
        condition: service_started
    ports:
     - "5001:5001"
    volumes:
      - "./logs:/drivers/logs"
    # environment:
    #   - LD_LIBRARY_PATH=/xtomo/vendor/ximea/libs/libusb/X64:/xtomo/vendor/ximea/libs/libraw1394/X64:/xtomo/vendor/ximea/api/X64

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always
  
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis
    restart: always

  tomograph_server:
    build: .
    container_name: rbtm-tomograph-server
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    volumes:
      - "./logs:/drivers/logs"
    devices:
      - "/dev/ttyACM2:/dev/ttyACM2"
      - "/dev/ttyACM1:/dev/ttyACM1"
      - "/dev/ttyACM0:/dev/ttyACM0"
      - ${XIMEA_CAMERA_DEVICE}
      - "/dev/ximc/0000037A:/dev/ximc/0000037A"
      - "/dev/ximc/00000271:/dev/ximc/00000271"
    environment:
      - LD_LIBRARY_PATH=/xtomo/vendor/ximea/libs/libusb/X64:/xtomo/vendor/ximea/libs/libraw1394/X64:/xtomo/vendor/ximea/api/X64
    command: python tomograph_server.py